In [54]:
### 해결방법 - Weight initialization:세이비어(Xavie)/ 글로럿(Glorot)

In [73]:

import torch
import torch.nn as nn


class Net(nn.Module):
    # 모델의 구성요소 생성및 구조 설정 : init의 역할
    def __init__ (self):
        super(Net, self) .__init__() #Net,self 써도 되고 안써도 됨

        self.fc1 = nn.Linear(8, 4)
        self.fc2 = nn.Linear(4, 2)
        self.drop=nn.Dropout(0.5)
        self.fc3 = nn.Linear(2, 1)

    def forward(self, x):
        return self.fc3(self.fc2(self.fc1(x)))

In [74]:
## 모델 인스턴스 생성
model=Net()


In [75]:
## 모델 인스턴스 속성 확인 
model.fc1

Linear(in_features=8, out_features=4, bias=True)

In [76]:
##모델 인스턴스 속성 확인
# 모델의 특정 층 추출
model.fc2.weight,model.fc2.bias

(Parameter containing:
 tensor([[-0.2605,  0.1839, -0.2204, -0.4311],
         [-0.4066, -0.4993,  0.0245, -0.0121]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1570, -0.3092], requires_grad=True))

In [77]:
model.parameters()

<generator object Module.parameters at 0x0000025408182EB0>

In [78]:
for param in model.parameters():
    print(param,end='\n\n')

Parameter containing:
tensor([[ 0.2680,  0.3532,  0.2671,  0.2760,  0.0639,  0.1784,  0.2104,  0.0564],
        [ 0.2733,  0.3373, -0.0631, -0.0470,  0.0129,  0.2844,  0.0695,  0.3471],
        [-0.1461, -0.2350,  0.2121, -0.2499,  0.0563, -0.1474, -0.1785, -0.0705],
        [ 0.1199, -0.0372, -0.0717,  0.2585,  0.3214,  0.0327, -0.3454,  0.1715]],
       requires_grad=True)

Parameter containing:
tensor([-0.3031, -0.1762, -0.1581,  0.2913], requires_grad=True)

Parameter containing:
tensor([[-0.2605,  0.1839, -0.2204, -0.4311],
        [-0.4066, -0.4993,  0.0245, -0.0121]], requires_grad=True)

Parameter containing:
tensor([ 0.1570, -0.3092], requires_grad=True)

Parameter containing:
tensor([[0.6560, 0.4216]], requires_grad=True)

Parameter containing:
tensor([0.2945], requires_grad=True)


In [79]:
for param in model.named_parameters():
    print(param,end='\n\n')

('fc1.weight', Parameter containing:
tensor([[ 0.2680,  0.3532,  0.2671,  0.2760,  0.0639,  0.1784,  0.2104,  0.0564],
        [ 0.2733,  0.3373, -0.0631, -0.0470,  0.0129,  0.2844,  0.0695,  0.3471],
        [-0.1461, -0.2350,  0.2121, -0.2499,  0.0563, -0.1474, -0.1785, -0.0705],
        [ 0.1199, -0.0372, -0.0717,  0.2585,  0.3214,  0.0327, -0.3454,  0.1715]],
       requires_grad=True))

('fc1.bias', Parameter containing:
tensor([-0.3031, -0.1762, -0.1581,  0.2913], requires_grad=True))

('fc2.weight', Parameter containing:
tensor([[-0.2605,  0.1839, -0.2204, -0.4311],
        [-0.4066, -0.4993,  0.0245, -0.0121]], requires_grad=True))

('fc2.bias', Parameter containing:
tensor([ 0.1570, -0.3092], requires_grad=True))

('fc3.weight', Parameter containing:
tensor([[0.6560, 0.4216]], requires_grad=True))

('fc3.bias', Parameter containing:
tensor([0.2945], requires_grad=True))


[배치 정규화]

In [80]:


class Model(nn.Module):

    def __init__(self):

        super(Model, self) .__init__()
        self.fc1 = nn.Linear(100, 50)
        
        self.bn = nn.BatchNorm1d(num_features=50)
        
        self.relu = nn. ReLU()
        
        self.fc2 = nn.Linear(50, 10)

In [81]:
def forward(self, x):
    X = self.fc1(x)
    
    X = self.bn(x)
    
    X = self.relu(x)
    X = self.fc2(x)

    return x

- Layer의 가중치 설정

In [82]:
#uniform_으로 가중치 설정 
nn.init.xavier_uniform_(model.fc1.weight)

Parameter containing:
tensor([[ 0.1554,  0.6223,  0.2500, -0.4702,  0.1257, -0.4717, -0.1931,  0.2636],
        [-0.0707, -0.3300,  0.3307, -0.3116, -0.5571,  0.3389,  0.2910, -0.1462],
        [ 0.1441,  0.3044, -0.4545, -0.3346, -0.5489, -0.3784,  0.2287,  0.4932],
        [-0.4235, -0.0176, -0.6251, -0.5711,  0.2378,  0.5422, -0.3689,  0.2213]],
       requires_grad=True)

In [83]:
# 세비어 알고리즘의 가중치 초기화 
nn.init.xavier_uniform_(model.fc1.weight)

Parameter containing:
tensor([[-0.0870,  0.3105, -0.1689,  0.3151, -0.6863, -0.2206,  0.3487,  0.2177],
        [-0.1214, -0.0723, -0.3344, -0.1738,  0.3212, -0.0304, -0.5774, -0.2960],
        [ 0.3694, -0.2712,  0.2083,  0.5218, -0.5150,  0.0834,  0.3444,  0.1706],
        [ 0.5520, -0.5483,  0.4512, -0.6357, -0.5089,  0.2187, -0.5845, -0.5158]],
       requires_grad=True)

In [84]:
#헤 알고리즘의 가중치 초기화(kaiming he씨에 의해 만들어졌음)
nn.init.kaiming_uniform_(model.fc1.weight)

Parameter containing:
tensor([[-0.1286, -0.8120, -0.5381,  0.5872,  0.0491,  0.5878,  0.4934, -0.6117],
        [-0.3627, -0.5486, -0.8242,  0.5452,  0.0948,  0.6776,  0.4105,  0.5690],
        [ 0.4423, -0.7748, -0.4785,  0.5208, -0.3668,  0.4940, -0.8572, -0.7170],
        [ 0.0145, -0.7747,  0.6040, -0.0613, -0.3996, -0.3077,  0.2178,  0.4900]],
       requires_grad=True)

In [85]:
# 해결 방법
for name,child in model.named_children():
    nn.init.xavier_uniform_(child.weight)

AttributeError: 'Dropout' object has no attribute 'weight'

In [86]:
#fc2,fc3 layer에 대하여 xavier normal initialization 설정
for name,child in model.named_children():
    for param in child.parameters():
        if name in ['fc2','fc3']: #원하는 layer 이름 지정
            nn.init.xavier_normal_(child.weight)

In [87]:
#모델 구성 모든 레이어 가져오기
for child in model.children():
    print(child,end='\n\n')

for child in model.named_children():
    print(child,end='\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Dropout(p=0.5, inplace=False)

Linear(in_features=2, out_features=1, bias=True)

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('drop', Dropout(p=0.5, inplace=False))

('fc3', Linear(in_features=2, out_features=1, bias=True))


## [텐서 보드]

In [88]:
# 텐서플로우를 시각화 해주는 친구

In [89]:
model=Net()
print(model)

from torchinfo import summary
summary(model) #Param # 은 각 가중치와 bias의 개수(9(8+1)*4=36,)=피쳐 개수+bias 1개* 퍼셉트론 개수
#drop ㅐㅕㅅdms dustksdmf dksgksek. 

Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (drop): Dropout(p=0.5, inplace=False)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Dropout: 1-3                           --
├─Linear: 1-4                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [89]:
# 파일 저장 방법

In [ ]:
# torch.save(model,'../data/model/mymodel.pt')


In [ ]:
# mymodel=torch.load('../data/model/mymodel.pt')
# mymodel

In [90]:
### ===> 검증 및 테스트 진행함수 
# def testing(data):
    # 학습모드 => 정규화,경사하강법,드랍아웃 등의 기능 활성화
# MODEL.eval()
# 
# with torch.no_grad():
#     
#     data=data.to(DEVICE)
#     
#     #학습 
#     pre_target =MODEL(data)
#     
#     F.softmax(pre_target)
#     
    