### Tensor 원소/요소 접근
- 인덱싱과 슬라이싱

In [30]:
import torch

In [31]:
# 텐서 생성
points=torch.tensor([[4.,2.],[5.,3.],[6.,4.]],dtype=torch.int16)
points

C:\Users\kdp\AppData\Local\Temp\ipykernel_2476\767740695.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points=torch.tensor([[4.,2.],[5.,3.],[6.,4.]],dtype=torch.int16)


tensor([[4, 2],
        [5, 3],
        [6, 4]], dtype=torch.int16)

In [32]:
# 텐서의 원소 1개 접근
# 데이터 3 추출
print(points[1,1])

#마지막 데이터 4 추출
print(points[2,1],points[-1,-1])

tensor(3, dtype=torch.int16)
tensor(4, dtype=torch.int16) tensor(4, dtype=torch.int16)


In [33]:
#1번 행부터 나머지 모든 행 추출
print(points[1:])

tensor([[5, 3],
        [6, 4]], dtype=torch.int16)


In [34]:
# 차원 늘리기

In [35]:
t1=torch.rand(2,3,1)
t1

tensor([[[0.4048],
         [0.4221],
         [0.5550]],

        [[0.8419],
         [0.2025],
         [0.3768]]])

In [36]:
t1=torch.rand(2,3,1,1) # 3행 1열 짜리가 차원이 늘어남(4차원)
t1

tensor([[[[0.3449]],

         [[0.1412]],

         [[0.8660]]],


        [[[0.7915]],

         [[0.6905]],

         [[0.5667]]]])

In [37]:
t1=torch.randn(2,3,1) #3행 1열 이 두개,3차원
t1

tensor([[[ 0.2857],
         [ 1.0552],
         [ 0.3491]],

        [[-1.1631],
         [ 0.7617],
         [ 0.7679]]])

## 브로드캐스팅 연산 

In [38]:
m1= torch.FloatTensor([[1.,2.]])
m2= torch.FloatTensor([[3]])

print(f'm1.shape =>{m1.shape},m2.shape =>{m2.shape}')
m3=m1+m2

m1.shape =>torch.Size([1, 2]),m2.shape =>torch.Size([1, 1])


In [39]:
print(f'm3.shape => {m3.shape}\nm3=>\n{m3}') #1행 2열의 2차원

m3.shape => torch.Size([1, 2])
m3=>
tensor([[4., 5.]])


In [40]:
m1= torch.FloatTensor([[1.,2.]])#1행 2열
m2= torch.FloatTensor([[3],[4]])#2행 1열

print(f'm1.shape =>{m1.shape},m2.shape =>{m2.shape}')
m3=m1+m2

m1.shape =>torch.Size([1, 2]),m2.shape =>torch.Size([2, 1])


In [41]:
print(f'm3.shape => {m3.shape}\nm3=>\n{m3}') #1행 2열의 2차원  [1,2]+ [3] 의 합
#                                                                   [4]

m3.shape => torch.Size([2, 2])
m3=>
tensor([[4., 5.],
        [5., 6.]])


In [44]:
m3=m1*m2  
print(f'm3.shape => {m3.shape}\nm3=>\n{m3}')  #각 항목끼리 곱해짐...

m3.shape => torch.Size([2, 2])
m3=>
tensor([[3., 6.],
        [4., 8.]])


In [47]:
m3=m1*m2  
m4=m1.mul(m2)
print(f'm3.shape => {m3.shape}\nm3=>\n{m3}')
print(f'm4.shape => {m4.shape}\nm4=>\n{m4}')

m3.shape => torch.Size([2, 2])
m3=>
tensor([[3., 6.],
        [4., 8.]])
m4.shape => torch.Size([2, 2])
m4=>
tensor([[3., 6.],
        [4., 8.]])


In [48]:
print(f'm4.shape => {m4.shape}\nm4=>\n{m4}')

m4.shape => torch.Size([2, 2])
m4=>
tensor([[3., 6.],
        [4., 8.]])


In [49]:
# 원소 단위 연산 수행 메서드들 
m1.add(m2),m1.sub(m2),m1.mul(m2),m1.div(m2)

(tensor([[4., 5.],
         [5., 6.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[3., 6.],
         [4., 8.]]),
 tensor([[0.3333, 0.6667],
         [0.2500, 0.5000]]))

In [50]:
# 피쳐 3개 (가중치 w는 피쳐의 개수를 따라가게 될 것이다.)
# 선형회귀=y=wx+b=>wx1+w2x2+w3x3+b
#그런데 피쳐가 [1,2,3] 이런식의 1차원으로가 아니라 [[1,2,3],[1,2,3]으로 들어온다면 어떻게 할 것인가.

In [ ]:
#1,2,3
#4,5,6