# 텐서 연결 & 결합

In [1]:
# 모듈 로딩
import torch

In [54]:
# 텐서 데이터 생성(동일 난수 생성 코드)
torch.manual_seed(12)
#임의의 0<=~<1 실수
X=torch.rand(2,10) #0에서 1사이 값,2행 10열로 표현하라
#임의의 정수 :low<=~<high
y=torch.randint(0,2,(10,))  #1차원 10개,정수
y2= torch.randint(0,2,(2,10)) #2행 10열,정수
#randint(행개수,열개수)

In [24]:
print(y2)
print(X)

tensor([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456]])


In [20]:
print(f'X=> {X.shape},{X.ndim}D')
print(f'y=> {y.shape},{y.ndim}D')
print(f'y2=> {y2.shape},{y2.ndim}D')

X=> torch.Size([2, 10]),2D
y=> torch.Size([10]),1D
y2=> torch.Size([2, 10]),2D


In [30]:
#tensor 연결 cat([텐서1,텐서2,....])
xy1=torch.cat([X,y2],dim=1)  #dim=0은 행방향
print(f'xy1=> {xy1.shape},{xy1.ndim}D')

xy1=> torch.Size([2, 20]),2D


In [31]:
#tensor 연결 cat([텐서1,텐서2,....])
xy1=torch.cat([X,y2],dim=0)
print(f'xy1=> {xy1.shape},{xy1.ndim}D')

xy1=> torch.Size([4, 10]),2D


In [32]:
#FloatTensor 위로 쌓는 것
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

torch.stack([x,y,z])
torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [44]:
#행단위로(세로)로 최대값 및 최대값의 인덱스
max_value=xy1.max(dim=1)[0]  #dim=0은 가로 기준, dim=1은 세로 기준
max_index=xy1.max(dim=1)[1]

In [45]:
max_value,max_index

(tensor([0.7312, 0.9790, 1.0000, 1.0000]), tensor([8, 6, 0, 2]))

In [46]:
# 열 단위(가로)로 최대값 및 최대값의 인덱스
max_value=xy1.max(dim=0)[0]
max_index=xy1.max(dim=0)[1]

max_value,max_index

(tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
         0.7224]),
 tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

In [51]:
import pandas as pd
data=pd.DataFrame({'A':[10,11],'B':[20,22],'C':[30,33]})
data

A   B   C
0  10  20  30
1  11  22  33

In [52]:
data.max(),data.max(axis=0)

(A    11
 B    22
 C    33
 dtype: int64,
 A    11
 B    22
 C    33
 dtype: int64)

In [53]:
data.max(axis=1)

0    30
1    33
dtype: int64