### 텐서(Tensor) 살펴보기
-Pytorch에서 데이터 저장 자료형
- 모델 입력(input),출력(outpu)데이터 형태

- 모듈로딩

In [1]:
import torch

-텐서 속성 관련 함수

In [18]:
#매개변수: 텐서 인스턴스,텐서 변수명 
def print_attribute(tensor,name):
    print(f'[Tensor {name}\'s Attributes:]')
    print(f'-tensor.shape:{tensor.shape}')
    print(f'-tensor.ndim:{tensor.ndim}D')
    print(f'-tensor.dtype:{tensor.dtype}')
    print(f'-tensor.device:{tensor.device}')
    print(f'-tensor.requires_grad:{tensor.requires_grad}')
    print(f'-tensor.data\n{tensor.data}')

## Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예)IntTensor(),FloatTensor(),BoolTensor()

In [40]:
#정수 타입 텐서 생성
t1=torch.IntTensor(10) #=> 얘는 스칼라가 된다.
t2=torch.IntTensor([10.,20.])#= > 1차원(벡터)이 된다.정수를 넣어야 하는 부분에 실수를 넣으면 warning이 뜬다.데이터 손실이 있을 수 있기 때문이다.
t3=torch.BoolTensor([1,1,0,-1])
t4=torch.FloatTensor([10,20])


C:\Users\kdp\AppData\Local\Temp\ipykernel_4068\2698144426.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2=torch.IntTensor([10.,20.])#= > 1차원이 된다.


In [35]:
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([10])
-tensor.ndim:1D
-tensor.dtype:torch.int32
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([176166384,      1053,         0,         0,         0,         0,
                0,         0,         0,         0], dtype=torch.int32)


In [36]:
print_attribute(t2,'t2')

[Tensor t2's Attributes:]
-tensor.shape:torch.Size([2])
-tensor.ndim:1D
-tensor.dtype:torch.int32
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([10, 20], dtype=torch.int32)


In [37]:
print_attribute(t3,'t3')

[Tensor t3's Attributes:]
-tensor.shape:torch.Size([4])
-tensor.ndim:1D
-tensor.dtype:torch.bool
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([ True,  True, False,  True])


In [38]:
print_attribute(t4,'t4')

[Tensor t4's Attributes:]
-tensor.shape:torch.Size([2])
-tensor.ndim:1D
-tensor.dtype:torch.float32
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([10., 20.])


In [39]:
#특정 데이터 타입을 정해놓고 값을 채우는 방법을 배웠다...

## Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()


In [41]:
t1=torch.tensor(10) #scalar 데이터,int
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([])
-tensor.ndim:0D
-tensor.dtype:torch.int64
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
10


In [42]:
t1=torch.tensor(10.) #scalar 데이터,float32
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([])
-tensor.ndim:0D
-tensor.dtype:torch.float32
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
10.0


In [44]:
t1=torch.tensor(10.,dtype=torch.int32) #scalar 데이터,float32를 넣었으나 dtype=torch.타입으로 원하는 타입으로 형태를 바꿀수 있다. 다만 warning이 생긴다.
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([])
-tensor.ndim:0D
-tensor.dtype:torch.int32
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
10


C:\Users\kdp\AppData\Local\Temp\ipykernel_4068\4226502719.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t1=torch.tensor(10.,dtype=torch.int32) #scalar 데이터,float32를 넣었으나 dtype=torch.타입으로 원하는 타입으로 형태를 바꿀수 있다. 다만 warning이 생긴다.


In [46]:
#dtype 매개변수: 원하는 데이터 타입 지정 가능
t1=torch.tensor(10.,dtype=torch.bool) #
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([])
-tensor.ndim:0D
-tensor.dtype:torch.bool
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
True


In [47]:
t1=torch.tensor([1,2,3],dtype=torch.int8) #1D데이터
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([3])
-tensor.ndim:1D
-tensor.dtype:torch.int8
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([1, 2, 3], dtype=torch.int8)


In [48]:
t1=torch.tensor([[1,2,3]],dtype=torch.int8) #2D데이터
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([1, 3])
-tensor.ndim:2D
-tensor.dtype:torch.int8
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([[1, 2, 3]], dtype=torch.int8)


In [49]:
t1=torch.tensor([[[1,2,3]]],dtype=torch.int8) #3D데이터
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([1, 1, 3])
-tensor.ndim:3D
-tensor.dtype:torch.int8
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([[[1, 2, 3]]], dtype=torch.int8)


## Tensor 생성 (3) 특정 값으로 텐서 생성 => torch.zeros(),torch.ones,torch.oneslike,torch.zeros_like,full_like(원하는 수)

In [71]:
#0으로 채운 텐서

In [72]:
t1=torch.zeros(5)
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([5])
-tensor.ndim:1D
-tensor.dtype:torch.float32
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([0., 0., 0., 0., 0.])


In [73]:
t1=torch.zeros((5,5),dtype=torch.int8) #5행 5열
print_attribute(t1,'t1')

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([5, 5])
-tensor.ndim:2D
-tensor.dtype:torch.int8
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


In [74]:
#1로 채우기
t1=torch.ones((2,4))  #2행 4열
print_attribute(t1,'t1')   

[Tensor t1's Attributes:]
-tensor.shape:torch.Size([2, 4])
-tensor.ndim:2D
-tensor.dtype:torch.float32
-tensor.device:cpu
-tensor.requires_grad:False
-tensor.data
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [75]:
#이미지 데이터를 가지고 왔는데 높이가 300이고 너비가 150인 경우, 전부 같지만 1로만 채우고 싶다면, ones_like나 zeros_like를 사용한다.

In [76]:
#이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like,ones_like

In [77]:
img=torch.tensor([[2,3,4,5,6,7],[2,3,4,5,6,7]])
print(img.shape)

torch.Size([2, 6])


In [78]:
zero_img=torch.zeros_like(img)
print(zero_img)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [79]:
zero_img=torch.ones_like(img)
print(zero_img)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])


In [80]:
full_img=torch.full_like(img,7)  #7로 채우기
print(full_img)

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [81]:
# 대각선 방향으로 1채우기
t1=torch.eye(5)
print(t1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [82]:
t1=torch.eye(3)
print(t1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Tensor 생성 (4) 특정 값으로 텐서 생성 => torch.rand(),torch.randn(),torch.randint()

In [88]:
torch.manual_seed(12)     #랜덤 초기값 설정
t5=torch.rand(2,3)
t6=torch.randn(2,3)  #standard normal분포 (정규분포) 에서 랜덤 생성
t7=torch.randint(low=1,high=10,size=(2,3)) #[low,high) low <=값<high

In [89]:
t5

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

In [90]:
t6


tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])

In [91]:
t7

tensor([[8, 4, 6],
        [2, 2, 2]])

## Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(),torch.as_tensor(),tensor()

In [92]:
#데이터 생성 
import numpy as np

data=np.array([11,22,33])
print(data,type(data))

[11 22 33] <class 'numpy.ndarray'>


In [93]:
t1=torch.from_numpy(data)
print(t1)

tensor([11, 22, 33], dtype=torch.int32)


In [94]:
t2=torch.as_tensor(data)
print(t2)

tensor([11, 22, 33], dtype=torch.int32)


In [95]:
t3=torch.tensor(data)
print(t2)

tensor([11, 22, 33], dtype=torch.int32)


In [99]:
# ndarray 원소 변경
data[0]=100  #인덱스 사용

In [103]:
print(data,t1,t2,t3,sep='\n')
#from_numpy랑 as_tensor는 복사본이므로, 위의 값이 바뀌면 자기들도 같이 바뀐다( 데이터 공유)
#tensor()로 생성하면 ===> 복사본 생성

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
