### Tensor shape )변경
- reshape(),view(): 원소 갯수가 유지됨, 기존 텐서 공유함

In [113]:
#모듈로딩
import torch

In [114]:
#텐서 데이터 생성
t1=torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape,t1.ndim)

torch.Size([2, 3]) 2


In [115]:
#[2,3] ====> [3,2] 형태변환:원소 동일 6개
t1.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [116]:
#[2,3] ====> [6,1] 형태변환:원소 동일 6개
t1.view(6,1)


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [117]:
#[2,3] ====> [6,1] 형태변환:원소 동일 6개
# -1: 열은 고정 되어 있고, 나머지 원소 수를 알아서 할당
t1.view(-1,1) #6개 줄테니까 1개짜리 행이 되도록 알아서 줘라

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [118]:
#[2,3] ===> [6,1] 형태 변경: 원소 동일 6개
# -1: 열은 고정 되어 있고, 나머지 원소 수를 알아서 할당
t1.view(6,1) #6개 줄테니까 1개짜리 행이 되도록 알아서 줘라

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [119]:
# tensor.reshape()
t1.reshape(6,1) 

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [120]:
# tensor.reshape()
t1.reshape(-1,3)   #-1의 차원의 크기를 자동으로 계산하라는 것

tensor([[1, 2, 3],
        [4, 5, 6]])

In [121]:
# # 원소의 수가 유지 되어야함(t1 원소수 6개) 즉, 7은 줄 수 없음
# t1.reshape(-1,7)   

## 전치 : 열과 행 변경

In [122]:
print(t1.shape)  #T를 통해 행렬이 변경

t2=t1.T
print(t2,t2.shape,t2.is_contiguous()) #False가 뜬다

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2]) False


In [123]:
# RuntimeError: view size is not compatible with input tensor's size and stride
# t2.view(-1,6)  #오류가 뜬다(transpose 썼을때, view는 안되고 reshape은 됨)

In [124]:
t3=t2.reshape(-1,6)  #얘는 문제가 없다
print(t3,t3.is_contiguous())     #얘는 True 로 뜬다.

tensor([[1, 4, 2, 5, 3, 6]]) True


## 3 텐서 데이터의 메모리 저장 정보 즉 메타데이터
- 현재 저장 형태,검색 방향 정보,시작 정보

In [125]:
t1=torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape,t1.ndim)
print(f't1.storage()=>{t1.storage()}')
print(f't1.storage_offset()=>{t1.storage_offset()}') #저장소의 오프셋이 어디인가
print(f't1.stride()=>{t1.stride()}') #다음 줄로 넘어가는데 필요한 수  (다음행까지 개수,바로  옆까지 개수)
print(f't1.is_contiguous()=>{t1.is_contiguous()}')

torch.Size([2, 3]) 2
t1.storage()=> 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset()=>0
t1.stride()=>(3, 1)
t1.is_contiguous()=>True


In [126]:
t2=t1.view(-1,2)  #메모리 읽어올때 2줄로 표현해라....(2열로 변경하여 t2) 생성
print(f't2.storage()=>{t2.storage()}')
print(f't2.storage_offset()=>{t2.storage_offset()}')
print(f't2.stride()=>{t2.stride()}') 
print(f't2.is_contiguous()=>{t2.is_contiguous()}') #연속적인가?
#transpose의 경우, view는 안되고 reshape은 되는데, view의 경우 바꾸었을때 연속적이지 못해서 안되고,
#reshape의 경우는 복사본으로 아예 새로 만들어 주기 때문에 됨(아예 주소자체가 바뀜)

#transpose는 스트라이드 값이 바뀌게 됨

t2.storage()=> 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2.storage_offset()=>0
t2.stride()=>(2, 1)
t2.is_contiguous()=>True


In [127]:
import numpy as np
a=np.array([1,2,3])
a.squeeze()

array([1, 2, 3])

### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze() : 텐서에서 차원이 1인 것 추가

In [128]:
# 데이터 생성
t1=torch.tensor([[1,2],[3,4]])
t2=torch.tensor([[1,2,3,4]])
t3=torch.tensor([[[1,2,3,4]]])


In [129]:
print(f't1=> {t1.shape},{t1.ndim}D')
print(f't2=> {t2.shape},{t2.ndim}D')
print(f't3=> {t3.shape},{t3.ndim}D')

t1=> torch.Size([2, 2]),2D
t2=> torch.Size([1, 4]),2D
t3=> torch.Size([1, 1, 4]),3D


In [130]:
t11=t1.squeeze()
t22=t2.squeeze()
t33=t3.squeeze()
t44=t3.squeeze(dim=2) #t3의 3번째 차원을 축소하는 것을 의미, 특정 부분의 차원 축소,3번쨰 차원이 제거된 텐서
print(f't1 차원 축소 => {t11.shape},{t11.ndim}D,{t11.data_ptr()}') #얘는 따로 줄여줄게 없음
print(f't2 차원 축소 => {t22.shape},{t22.ndim}D,{t22.data_ptr()}')
print(f't3 차원 축소 => {t33.shape},{t33.ndim}D,{t33.data_ptr()}')
print(f't3 차원 축소 => {t44.shape},{t44.ndim}D,{t44.data_ptr()}')

t1 차원 축소 => torch.Size([2, 2]),2D,3383800955648
t2 차원 축소 => torch.Size([4]),1D,3383800955776
t3 차원 축소 => torch.Size([4]),1D,3383800955840
t3 차원 축소 => torch.Size([1, 1, 4]),3D,3383800955840


In [131]:
#[데이터수] 1차
#[데이터:행,피쳐:열]
#[데이터수,채널,높이,너비]

In [132]:
t1

tensor([[1, 2],
        [3, 4]])

In [133]:
t11

tensor([[1, 2],
        [3, 4]])

In [134]:
t2

tensor([[1, 2, 3, 4]])

In [135]:
t22

tensor([1, 2, 3, 4])

In [136]:
t3

tensor([[[1, 2, 3, 4]]])

In [137]:
t33

tensor([1, 2, 3, 4])

In [138]:
t1.shape

torch.Size([2, 2])

In [139]:
## 원소/요소 수 변경 없이 차원 증가 시키기 => torch.unsqueeze(dim)
print(f't1정보 => {t1.shape},{t1.ndim}D,{t1.data_ptr()},{t1.stride()}')


t1정보 => torch.Size([2, 2]),2D,3383800955648,(2, 1)


In [149]:
t11=t1.unsqueeze(dim=0) # 0번쨰 차원에 새로운 차원 추가
t22=t1.unsqueeze(dim=-1) #새로운 차원을 마지막 위치에 추가

print(f't1 차원 추가 => {t11.shape},{t11.ndim}D,{t11.data_ptr()},{t11.stride()}')
print(f't2 차원 추가 => {t22.shape},{t22.ndim}D,{t22.data_ptr()},{t11.stride()}')


t1 차원 추가 => torch.Size([1, 1, 3, 2]),4D,3383800897728,(6, 6, 2, 1)
t2 차원 추가 => torch.Size([1, 3, 2, 1]),4D,3383800897728,(6, 6, 2, 1)


###  Tensor 차원/형태 변경

In [141]:
t1=torch.tensor([[[1,2],[11,22],[44,55]]])

print(f't1 => {t1.shape},{t1.ndim}D')

t1 => torch.Size([1, 3, 2]),3D


In [142]:
# 2개의 차원을 변경하는 메서드()
t11=t1.transpose(0,2) #0번 자리를 2번으로 바꿔줘  즉 (1,3,2) => 1과 3의 위치(0과 2번)이 바뀌면서 
# (2,3,1) 즉 3행 1열 짜리가 2장 나오게 되는 것
print(f't11 => {t11.shape},{t11.ndim}D')

t11 => torch.Size([2, 3, 1]),3D


In [143]:
t22

tensor([[[1],
         [2]],

        [[3],
         [4]]])

In [144]:
# 모든의 차원을 변경하는 메서드()
t22=t1.permute(1,2,0) 
print(f't22 => {t22.shape},{t22.ndim}D')     #[1,3,2]=> [3,2,1]로 변경

t22 => torch.Size([3, 2, 1]),3D


In [145]:
print(f't22 => {t22.shape},{t22.ndim}D')

t22 => torch.Size([3, 2, 1]),3D


In [146]:
print(f'{t1.data_ptr()},{t22.data_ptr()},{t11.data_ptr()}')

3383800897728,3383800897728,3383800897728


In [147]:
# t1[None].shape()