In [47]:
import torch

## 1. 화면상에서 Pytorch에서 데이터를 저장하는 단위는 ( )입니다.

답:텐서

## 2. 1번 문제에 해당하는 것의 특징을 간력히 설명해 보세요.

파이토치에서 데이터를 저장하는 단위로서 차원에 따라서 
1차원(벡터),2차원(행렬),3차원,4차원......등으로 나뉘어집니다.

## 3.Pytorch에서 정수형 데이터를 저장하는 데이터 타입을 모두 나열하세요. 간단한 데이터 타입의 크기 설명도 함께 작성하세요

#

## 4. Pytorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요.

In [48]:
torch.BoolTensor([10,-5,-1.4,7,0,-1,0])

tensor([ True,  True,  True,  True, False,  True, False])

## 5. 10개의 0 데이터를 2차원으로 저장 코드를 작성하세요.

In [62]:
t1=torch.zeros(1,10) # 왜 이렇게 되는 겨?
torch.zeros_like(t1)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 6. 5개의 1 데이터가 대각선으로 저장되는 2차원 저장 코드를 작성하세요.

In [50]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## 7. 5번에서 저장된 형태와 동일하지만 값이 3이 저장된 코드를 작성하세요.

In [66]:
torch.full_like(t1,3)


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 8. ndarray데이터를 Pytorch에 저장하는 코드를 작성하세요.

In [88]:
torch.randint(0,101,7)

TypeError: randint() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int high, tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int low, int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int low, int high, tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


## 9. 아래 조건에 맞는 데이터를 Pytorch에 저장하는 코드를 작성하세요.

In [80]:
# 텐서일때는 이미지 크기의 가로 세로값이 반대가 되면, 1픽셀은 0~255 사이의 값이다.
# torch.randint()

## 10. 아래 조건에 맞도록 코드를 작성하세요.

In [71]:
data1=torch.tensor([1,2,3,4,5,6,7,8,9,10])

(2)

In [86]:
data1=data1.reshape(1,2,5) # 원소가 10개니까 3차원 3개를 곲해서 10이 되면 된다....

(3) 

In [78]:
data1.transpose(0,2)

tensor([[[ 1],
         [ 6]],

        [[ 2],
         [ 7]],

        [[ 3],
         [ 8]],

        [[ 4],
         [ 9]],

        [[ 5],
         [10]]])

(4) 

In [79]:
data1.permute(0,2,1)

tensor([[[ 1,  6],
         [ 2,  7],
         [ 3,  8],
         [ 4,  9],
         [ 5, 10]]])

## 11. 아래 조건에 맞도록 코드를 작성하세요.

In [ ]:
#(1) 
t1=torch.tensor([[90,70,80],[70,100,80],[99,88,77]])

In [ ]:
#(2)
#디멘션 1

In [87]:
#(3) 
#디멘션 2


## 12. 아래 조건에 맞도록 코드를 작성하세요.

(1) 데이터를 저장

In [56]:
data1=torch.tensor([[90,70,80],[70,100,80],[99,88,77]])
data2=torch.tensor([5,2,0.7])

합

In [57]:
data1+data2

tensor([[ 95.0000,  72.0000,  80.7000],
        [ 75.0000, 102.0000,  80.7000],
        [104.0000,  90.0000,  77.7000]])

차

In [58]:
data1-data2

tensor([[85.0000, 68.0000, 79.3000],
        [65.0000, 98.0000, 79.3000],
        [94.0000, 86.0000, 76.3000]])

곱

In [59]:
data1*data2

tensor([[450.0000, 140.0000,  56.0000],
        [350.0000, 200.0000,  56.0000],
        [495.0000, 176.0000,  53.9000]])

나눗셈

In [60]:
data1/data2

tensor([[ 18.0000,  35.0000, 114.2857],
        [ 14.0000,  50.0000, 114.2857],
        [ 19.8000,  44.0000, 110.0000]])

In [61]:
data1.tensor.matmul()

AttributeError: 'Tensor' object has no attribute 'tensor'