### 데이터 로딩 및 텐서 변환 <hr>

# 모듈 로딩


In [5]:
import imageio.v2 as imageio   #이미지 데이터 관련 모듈
import torch     # Pytorch 텐서 및 기본 함수 관련 모듈

In [6]:
# 이미지 데이터 로딩
filename='../data/빽어택.jpg'

In [8]:
img_data=imageio.imread(filename)

In [12]:
print(img_data.shape,img_data.ndim)

(419, 420, 3) 3


In [14]:
# ndarray => tensor 변환 :[행(높이),열(너비),채널]
img_t1=torch.tensor(img_data)
img_t2=torch.from_numpy(img_data)
img_t3=torch.as_tensor(img_data)

In [16]:
#[행(높이),열(너비),채널] => [채널,행(높이),열(너비)]
img_t1.permute(2,0,1).shape  #채널을 앞으로 보냈음

torch.Size([3, 419, 420])

In [19]:
import csv
import numpy as np
file='../data/winequality-white.csv'

# [2-1] Pandas 사용한 데이터 로딩

In [25]:
wineq_numpy=np.loadtxt(file,dtype=np.float32,delimiter=';',skiprows=1)  #skiprows= 필요없는 행 버리기,delimiter:구분자

In [21]:
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [22]:
col_list=next(csv.reader(open(file),delimiter=';'))

# [2-2] Numpy 사용한 데이터 로딩

In [23]:
wineq=torch.from_numpy(wineq_numpy)

In [24]:
wineq.shape,wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [26]:
# _의 의미

In [28]:
t1=torch.tensor([-2,-7])

In [29]:
t1.abs(),t1

(tensor([2, 7]), tensor([-2, -7]))

In [30]:
t1.abs_(),t1

(tensor([2, 7]), tensor([2, 7]))