### softmax(), sigmoid() 함수 <hr>
- sigmoid(선형회귀결과값):y=wx+b 결과 1개를 전달 ===> 반환 :0.0~1.0 사이 값으로 변환 => 2진분류에 사용

- softmax() : y=wx+b 결과 여러개 전달 ===>여러개의 결과값의 합이 1.0이 되도록 변환  => 다중분류

## 모듈 로딩

In [25]:
import torch               #파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F     #파이토치 인공신경망 관련 함수들이 들어있음


In [26]:
# 임의 데이터 생성 
data1=torch.tensor([1,2,1,1,2])
data1.shape

torch.Size([5])

In [27]:
#시그모이드로 계산
F.sigmoid(data1)

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [28]:
# 소프트 맥스로 계산
data2=data1.unsqueeze(dim=0) #1주면 뒤에 붙고, 0주면 앞에 붙는다
data2.shape,data2

(torch.Size([1, 5]), tensor([[1, 2, 1, 1, 2]]))

In [29]:
input=torch.randn(2,3)  #2행 3열 랜덤으로 (0과 1사이의 값)
input
#ya=wx+b
#yb=wx+b
#yc=wx+b
#3개 합쳐져서 1.0으로...

tensor([[-0.1118, -0.4716,  1.1135],
        [ 1.7949, -0.5462, -1.2076]])

In [30]:
output=F.softmax(input)
output

C:\Users\kdp\AppData\Local\Temp\ipykernel_424\1895841654.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output=F.softmax(input)


tensor([[0.1960, 0.1367, 0.6673],
        [0.8727, 0.0840, 0.0433]])

In [31]:
output.sum(dim=1) #행마다 합계
# output.sum(dim=0) #열마다 합계

tensor([1., 1.])

In [35]:
output.max(dim=1)[1][0].item()

2

In [36]:
output.argmax(dim=1) #이것도 위에 거랑 비슷

tensor([2, 0])