In [1]:
## 모듈 로딩
import numpy as np


In [2]:
## ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 ==> zeros()
np.zeros(2)


array([0., 0.])

In [4]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [10]:
#1로 채워진 ndarray 객체 생성 : np.ones()
np.ones(10),np.ones(10,dtype=np.int32),np.ones((2,5),dtype=np.bool_)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [12]:
# 랜덤 데이터로 ndarrat객체 생성 ==> random
np.random.randint(1,5,(3,10)) #3행 10열을 1에서 5까지의 램덤 숫자로 만들어준다.

array([[1, 1, 4, 3, 3, 3, 3, 3, 4, 4],
       [1, 2, 4, 4, 3, 2, 1, 1, 2, 4],
       [3, 4, 1, 1, 1, 1, 3, 3, 2, 1]])

In [19]:
#0<=범위<1
np.random.rand(5,2),np.random.rand(3)

(array([[0.26462758, 0.3131681 ],
        [0.39204086, 0.21539289],
        [0.65356975, 0.12683035],
        [0.4136658 , 0.19503246],
        [0.77355994, 0.07920122]]),
 array([0.01125321, 0.28840265, 0.73097287]))

In [28]:
np.random.randn(5),np.random.randn(1,2,3)

(array([ 0.15989294, -1.20894816,  2.22336022,  0.39429521,  1.69235772]),
 array([[[-1.11281215,  1.63574754, -1.36096559],
         [-0.65122583,  0.54245131,  0.04800625]]]))

In [25]:
# 랜덤 고정
np.random.seed(4) 

In [39]:
np.random.randn(5)

array([ 0.85038687, -0.67690095, -1.12511459, -0.85295128, -1.10457461])

In [46]:
data=np.random.randn(10)
print(data)

np.random.shuffle(data)
print(data)

[-1.43738386  0.13375138  0.42395176 -0.20653741  0.48273896 -1.09737373
 -0.14527478 -0.90914768  0.74491863  0.53832361]
[-0.20653741 -1.09737373 -0.90914768 -0.14527478  0.13375138  0.48273896
  0.74491863  0.42395176  0.53832361 -1.43738386]


In [46]:
#지정된 범위 (arange)


In [47]:
#어디에서 어디까지 숫자만큼 생성np.linspace(어디,어디,숫자) 
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [49]:
data.sum(),data.max(),data.min()

(-1.4720331242928126, 0.7449186327365465, -1.4373838647938575)

In [50]:
data.argmax(),data.argmin()

(6, 9)